### ISSUE TITLE
Allow psr/log 2.0 (and 3.0?)

### ISSUE THREAD

**Issue by SunMar** [apioo/psx-http#1]
Hi,

Today I came across `psx/api` and when I tried to install it, initially composer wouldn't let me because `psx/http` would force a downgrade of `psr/log` from `2.0` to `1.0`. I think `1.x` and `2.0` [are pretty much the same](https://github.com/php-fig/log/compare/1.1.4...2.0.0?diff=unified) except that 2.0 is updated for PHP >= 8.0. I couldn't easily spot a true breaking change, and since most packages allow `^1.0 || ^2.0` it looks safe to do.

There also is `3.0` [which adds `void` return types](https://github.com/php-fig/log/compare/2.0.0...3.0.0), I think that only impacts someone if they're implementing the interface. Seems like you only type hint it in which case maybe even `^1.0 || ^2.0 || ^3.0` is possible for `psx/http`.

**Comment by chriskapp** [comment]
Yes, this makes sense, we can allow all versions and I have just merged the PR

**Comment by SunMar** [comment]
Thank you!

**Comment by SunMar** [comment]
@chriskapp Hi! It seems like you accidentally tagged 3.0.3 on the same commit as 3.0.2 (0c204fff8647d9b5e34e43908ae70e5376e978aa) instead of the merged commit that updates the `composer.json` (7cd8425c23d721d638a1f593832a0f5685d634bf). See below an excerpt from my `composer.lock` after updating. It's running on 3.0.3 but it's still only allowing `psr/log:^1.0`.

```
        {
            "name": "psx/http",
            "version": "v3.0.3",
            "source": {
                "type": "git",
                "url": "https://github.com/apioo/psx-http.git",
                "reference": "0c204fff8647d9b5e34e43908ae70e5376e978aa"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/apioo/psx-http/zipball/0c204fff8647d9b5e34e43908ae70e5376e978aa",
                "reference": "0c204fff8647d9b5e34e43908ae70e5376e978aa",
                "shasum": ""
            },
            "require": {
                "guzzlehttp/guzzle": "^7.0",
                "php": ">=8.0",
                "psr/http-message": "^1.0",
                "psr/log": "^1.0",
                "psx/uri": "^2.0"
            },
            ...etc...
```

**Comment by chriskapp** [comment]
Hey @SunMar sorry indeed my bad, I have just created a new tag which should point to the current version.

**Comment by SunMar** [comment]
Yes, can confirm now after running a `composer update` the `psr/log` package upgraded to `3.0` and some other Symfony packages that were apparently still on v5 now also managed to upgrade to v6. Thank you! :)
